---
http:
  address: ":8000"

ssrf_token: "REPLACE_THIS_WITH_YOUR_SECRET_VALUE"

logging:
  format: "console"
  timeEncoder: "ISO8601TimeEncoder"
  file: "ssrf-sheriff.log"

webhook: "REPLACE_THIS_WITH_YOUR_WEBHOOK"
healthcheck_url: "your_healthcheck_url"
